import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../styles/colors';

const ReportScreen = ({ navigation }) => {
  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Ionicons name="chevron-back" size={24} color={Colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Report</Text>
        <View style={{ width: 24 }} />
      </View>

      {/* Report Content */}
      <View style={styles.content}>
        <Text style={styles.reportText}>
          1.If you find that this service or the content generated by this service violates laws and regulations, internet or cultural management policies, social morality, or impacts normal social operations, or if it infringes on your legitimate rights (including but not limited to intellectual property, personal information, portrait rights, reputation rights, etc.), please contact us at any time to file a complaint or report. We will promptly investigate and confirm it. If your complaint or report is verified, we will immediately take reasonable measures such as stopping generation, stopping transmission, removing offending content, and correcting the algorithm model, and respond to you. Generally, the time for us to verify and provide feedback after receiving your complaint or report will not exceed 15 working days. If further verification is needed, we will communicate the current processing situation to you promptly.
        </Text>
        
        <Text style={styles.reportText}>
          2.If required by laws and regulations, we will report the problems found in this service or the content generated by this service to the relevant authorities.
        </Text>
        
        <Text style={styles.reportText}>
          3.You can report or file a complaint through the following channels:Report and complaint email: support@sayloai.com
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.text,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  reportText: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'left',
  },
});

export default ReportScreen;